services:
    ansible_wui_ansible.form_type.task:
        class: AnsibleWUI\AnsibleBundle\Form\Type\TaskType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
