imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AnsibleWUIUserBundle/Resources/config/services.yml" }
    - { resource: "@AnsibleWUIProjectBundle/Resources/config/services.yml" }
    - { resource: "@AnsibleWUICoreBundle/Resources/config/services.yml" }
    - { resource: "@AnsibleWUIAnsibleBundle/Resources/config/services.yml" }
    - { resource: "@AnsibleWUIHostBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    bundles:        [ ]

    filters:
        cssrewrite: ~
    assets:
        jquery:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jquery/dist/jquery.min.js'
        jqueryui:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jquery-ui/jquery-ui.min.js'

        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/components/bootstrap/dist/js/bootstrap.min.js'
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../vendor/components/bootstrap/dist/css/bootstrap.min.css'
                - '%kernel.root_dir%/../vendor/components/bootstrap/dist/css/bootstrap-theme.min.css'
            filters: [cssrewrite]

        bootstrap_css_map:
            inputs:
                - '%kernel.root_dir%/../vendor/components/bootstrap/dist/css/bootstrap.min.css.map'
                - '%kernel.root_dir%/../vendor/components/bootstrap/dist/css/bootstrap-theme.min.css.map'
            output: "css/bootstrap.css.map"

        bootstrap_glyphicons_ttf:
            inputs:
                - '%kernel.root_dir%/../vendor/components/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf'
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - '%kernel.root_dir%/../vendor/components/bootstrap/dist/fonts/glyphicons-halflings-regular.eot'
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - '%kernel.root_dir%/../vendor/components/bootstrap/dist/fonts/glyphicons-halflings-regular.svg'
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - '%kernel.root_dir%/../vendor/components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff'
            output: "fonts/glyphicons-halflings-regular.woff"
        bootstrap_glyphicons_woff2:
            inputs:
                - '%kernel.root_dir%/../vendor/components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2'
            output: "fonts/glyphicons-halflings-regular.woff2"

        fontawesome:
            inputs:
                - '%kernel.root_dir%/../vendor/components/font-awesome/css/font-awesome.min.css'
        fontawesome-woff:
            inputs:
                - '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff'
            output: "fonts/fontawesome-webfont.woff"
        fontawesome-woff2:
            inputs:
                - '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff2'
            output: "fonts/fontawesome-webfont.woff2"

        adminlte_js:
            inputs:
                - '%kernel.root_dir%/../vendor/components/AdminLTE/plugins/datepicker/bootstrap-datepicker.js'
                - '%kernel.root_dir%/../vendor/components/AdminLTE/plugins/daterangepicker/daterangepicker.js'
                - '%kernel.root_dir%/../vendor/components/AdminLTE/plugins/flot/jquery.flot.js'
                - '%kernel.root_dir%/../vendor/components/AdminLTE/plugins/flot/jquery.flot.time.js'
                - '%kernel.root_dir%/../vendor/components/AdminLTE/dist/js/app.min.js'

        adminlte_css:
            inputs:
                - '%kernel.root_dir%/../vendor/components/AdminLTE/dist/css/AdminLTE.css'
                - '%kernel.root_dir%/../vendor/components/AdminLTE/dist/css/skins/skin-red.css'
                - '%kernel.root_dir%/../vendor/components/AdminLTE/plugins/datepicker/datepicker3.css'
                - '%kernel.root_dir%/../vendor/components/AdminLTE/plugins/daterangepicker/daterangepicker-bs3.css'

        icheck_js:
            inputs:
                - '%kernel.root_dir%/../vendor/components/AdminLTE/plugins/iCheck/icheck.min.js'
        icheck_css:
            inputs:
                - '%kernel.root_dir%/../vendor/components/AdminLTE/plugins/iCheck/minimal/blue.css'

        datatables_js:
            inputs:
                - '%kernel.root_dir%/../vendor/components/AdminLTE/plugins/datatables/jquery.dataTables.min.js'
                - '%kernel.root_dir%/../vendor/components/AdminLTE/plugins/datatables/dataTables.bootstrap.min.js'
        datatables_css:
            inputs:
                - '%kernel.root_dir%/../vendor/components/AdminLTE/plugins/datatables/dataTables.bootstrap.css'

        moment_js:
            inputs:
                - '%kernel.root_dir%/../vendor/components/moment/min/moment.min.js'

        select2_js:
            inputs:
                - '%kernel.root_dir%/../vendor/components/select2/dist/js/select2.js'
        select2_css:
            inputs:
                - '%kernel.root_dir%/../vendor/components/select2/dist/css/select2.min.css'

        answui_js:
            inputs:
                - '%kernel.root_dir%/../src/AnsibleWUI/CoreBundle/Resources/public/js/bind.js'
                - '%kernel.root_dir%/../src/AnsibleWUI/CoreBundle/Resources/public/js/chart.js'
                - '%kernel.root_dir%/../src/AnsibleWUI/CoreBundle/Resources/public/js/datatable.js'
                - '%kernel.root_dir%/../src/AnsibleWUI/CoreBundle/Resources/public/js/filter.js'
                - '%kernel.root_dir%/../src/AnsibleWUI/CoreBundle/Resources/public/js/sortable.js'
                - '%kernel.root_dir%/../src/AnsibleWUI/CoreBundle/Resources/public/js/tags.js'
                - '%kernel.root_dir%/../src/AnsibleWUI/CoreBundle/Resources/public/js/script.js'

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AnsibleWUI\UserBundle\Entity\User
    profile:
        form:
            type: AnsibleWUI\UserBundle\Form\Type\ProfileType