ansible_wui_core:
    resource: "@AnsibleWUICoreBundle/Resources/config/routing.yml"
    prefix:   /

ansible_wui_project:
    resource: "@AnsibleWUIProjectBundle/Resources/config/routing.yml"
    prefix:   /

ansible_wui_user:
    resource: "@AnsibleWUIUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /